timestamp:
  # E.g. 2015-01-31T15:50:45.392
  - '\d{4}\-\d{2}\-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}'
  # E.g. 2015-01-31T15:50:45,392
  - '\d{4}\-\d{2}\-\d{2}T\d{2}:\d{2}:\d{2},\d{3}'
  # E.g. 2015-01-31 15:50:45
  - '\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2}'

delimiters: " \t\r\n:,!;%"

variables:
  int: '\-{0,1}\d+'
  float: '\-{0,1}[0-9]+\.[0-9]+'
  hex: '(0x){0,1}([0-9a-f]+)|([0-9A-F]+)'
  loglevel: '(INFO)|(DEBUG)|(WARN)|(ERROR)|(TRACE)|(FATAL)'
